export const github = require('./github.png')
export const email = require('./email.png')
export const stackoverflow = require('./stackoverflow.png')
export const linkedin = require('./linkedin.jpg')
export const sunflower = require('./sunflower-background.jpg')
export const JulieImage = require('./JulieImage.jpg')
